"""Unitree R1 (26 DOF) robot configuration for SONIC.

The R1 is a 1.2 m bipedal humanoid: 12 leg DOF, 2 waist, 10 arm and 2 head.
Compared to the G1 it has no wrist pitch/yaw (one roll DOF per wrist), no waist
pitch, and its bodies use different names -- ``pelvis_link`` rather than
``pelvis``, ``waist_yaw_link`` in place of ``torso_link``, ``*_wrist_roll_link``
in place of ``*_wrist_yaw_link``, and ``head_yaw_link`` in place of ``head_link``.
Config overrides for those names live in
``config/exp/manager/universal_token/all_modes/sonic_r1.yaml``.

Actuator gains, grouping and the standing pose come from a config that was
tested in simulation on simple R1 locomotion policies
(``holosoma/custom_assets/unitree.py::R1_CFG``), not from the G1 armature
formula used in ``g1.py``/``h2.py``.
"""

from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg
import isaaclab.sim as sim_utils

ASSET_DIR = "gear_sonic/data/assets"

# =============================================================================
# Joint / body ordering
# =============================================================================
# MuJoCo order: depth-first over the tree in gear_sonic/data/assets/robot_description/mjcf/r1.xml
# (generated by gear_sonic/data_process/make_r1_sonic_mjcf.py). This is also the
# order the retargeted .npz motion data uses for qpos[7:].
R1_MUJOCO_BODIES = [
    "pelvis_link",
    "left_hip_pitch_link",
    "left_hip_roll_link",
    "left_hip_yaw_link",
    "left_knee_link",
    "left_ankle_pitch_link",
    "left_ankle_roll_link",
    "right_hip_pitch_link",
    "right_hip_roll_link",
    "right_hip_yaw_link",
    "right_knee_link",
    "right_ankle_pitch_link",
    "right_ankle_roll_link",
    "waist_roll_link",
    "waist_yaw_link",
    "left_shoulder_pitch_link",
    "left_shoulder_roll_link",
    "left_shoulder_yaw_link",
    "left_elbow_link",
    "left_wrist_roll_link",
    "right_shoulder_pitch_link",
    "right_shoulder_roll_link",
    "right_shoulder_yaw_link",
    "right_elbow_link",
    "right_wrist_roll_link",
    "head_pitch_link",
    "head_yaw_link",
]

# All bodies in IsaacLab (PhysX) traversal order, including the root. This is
# breadth-first by tree depth, but the sibling order within a depth is PhysX's
# and does not follow the URDF declaration order -- head_pitch_link sorts ahead
# of the shoulders even though the URDF declares it last. Do not hand-predict
# this list; it is dumped from the live articulation and checked by
# gear_sonic/data_process/dump_r1_isaaclab_order.py.
R1_ISAACLAB_JOINTS = [
    "pelvis_link",
    # depth 1
    "left_hip_pitch_link",
    "right_hip_pitch_link",
    "waist_roll_link",
    # depth 2
    "left_hip_roll_link",
    "right_hip_roll_link",
    "waist_yaw_link",
    # depth 3
    "left_hip_yaw_link",
    "right_hip_yaw_link",
    "head_pitch_link",
    "left_shoulder_pitch_link",
    "right_shoulder_pitch_link",
    # depth 4
    "left_knee_link",
    "right_knee_link",
    "head_yaw_link",
    "left_shoulder_roll_link",
    "right_shoulder_roll_link",
    # depth 5
    "left_ankle_pitch_link",
    "right_ankle_pitch_link",
    "left_shoulder_yaw_link",
    "right_shoulder_yaw_link",
    # depth 6
    "left_ankle_roll_link",
    "right_ankle_roll_link",
    "left_elbow_link",
    "right_elbow_link",
    # depth 7
    "left_wrist_roll_link",
    "right_wrist_roll_link",
]


def _joint_of(body_name: str) -> str:
    """Return the joint driving ``body_name``.

    Every non-root R1 body owns exactly one joint and the names are regular
    (``*_link`` -> ``*_joint``); ``make_r1_sonic_mjcf.py`` asserts the one-joint
    -per-body part. G1 needs a lookup table here because ``torso_link`` is driven
    by ``waist_yaw_joint``, but R1 has no such irregularity.
    """
    return body_name.removesuffix("_link") + "_joint"


R1_MUJOCO_DOFS = [_joint_of(b) for b in R1_MUJOCO_BODIES[1:]]
R1_ISAACLAB_DOFS = [_joint_of(b) for b in R1_ISAACLAB_JOINTS[1:]]

# Index arrays: position i in the output = position mapping[i] in the input.
# Same semantics as the G1/H2 literals (verified against them):
#   MUJOCO_TO_ISAACLAB gathers a MuJoCo-ordered array into IsaacLab order.
R1_MUJOCO_TO_ISAACLAB_BODY = [R1_MUJOCO_BODIES.index(n) for n in R1_ISAACLAB_JOINTS]
R1_ISAACLAB_TO_MUJOCO_BODY = [R1_ISAACLAB_JOINTS.index(n) for n in R1_MUJOCO_BODIES]
R1_MUJOCO_TO_ISAACLAB_DOF = [R1_MUJOCO_DOFS.index(n) for n in R1_ISAACLAB_DOFS]
R1_ISAACLAB_TO_MUJOCO_DOF = [R1_ISAACLAB_DOFS.index(n) for n in R1_MUJOCO_DOFS]

R1_ISAACLAB_TO_MUJOCO_MAPPING = {
    "isaaclab_joints": R1_ISAACLAB_JOINTS,
    "isaaclab_to_mujoco_dof": R1_ISAACLAB_TO_MUJOCO_DOF,
    "mujoco_to_isaaclab_dof": R1_MUJOCO_TO_ISAACLAB_DOF,
    "isaaclab_to_mujoco_body": R1_ISAACLAB_TO_MUJOCO_BODY,
    "mujoco_to_isaaclab_body": R1_MUJOCO_TO_ISAACLAB_BODY,
}

# =============================================================================
# Articulation
# =============================================================================
# Effort limits are the real motor torques from the MJCF `actuatorfrcrange`.
# Exception: head_yaw reads 0.86 Nm in both the URDF and the MJCF while its
# velocity limit is 11 rad/s -- an upstream data bug (the retargeted motions
# drive head_yaw over [-1.455, 0] rad). It is raised to head_pitch's 33 Nm here.
EFFORT_LEG = 60.0
EFFORT_ANKLE = 50.0
EFFORT_WAIST = 60.0
EFFORT_SHOULDER = 60.0
EFFORT_ARM_DISTAL = 33.0
EFFORT_HEAD = 33.0

R1_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        fix_base=False,
        replace_cylinders_with_capsules=True,
        asset_path=f"{ASSET_DIR}/robot_description/urdf/r1/r1.urdf",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=4,
        ),
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0, damping=0)
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        # R1's pelvis sits ~0.71 m above the soles in this pose; the retargeted
        # motions average 0.693 m.
        pos=(0.0, 0.0, 0.70),
        joint_pos={
            ".*_hip_yaw_joint": 0.0,
            ".*_hip_roll_joint": 0.0,
            ".*_hip_pitch_joint": -0.28,
            ".*_knee_joint": 0.79,
            ".*_ankle_pitch_joint": -0.52,
            ".*_ankle_roll_joint": 0.0,
            "waist_roll_joint": 0.0,
            "waist_yaw_joint": 0.0,
            ".*_shoulder_pitch_joint": 0.28,
            ".*_shoulder_roll_joint": 0.0,
            ".*_shoulder_yaw_joint": 0.0,
            ".*_elbow_joint": 0.52,
            ".*_wrist_roll_joint": 0.0,
            "head_pitch_joint": 0.0,
            "head_yaw_joint": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    # G1 uses 0.9, but the retargeted reference motions sit exactly on R1's hard
    # limits for 18 of 26 joints (left_ankle_roll spans precisely +/-0.2618), so
    # a 0.9 soft limit would make the joint_limit reward punish correct tracking.
    soft_joint_pos_limit_factor=0.99,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[
                ".*_hip_yaw_joint",
                ".*_hip_roll_joint",
                ".*_hip_pitch_joint",
                ".*_knee_joint",
            ],
            effort_limit_sim=EFFORT_LEG,
            stiffness={
                ".*_hip_yaw_joint": 150.0,
                ".*_hip_roll_joint": 150.0,
                ".*_hip_pitch_joint": 200.0,
                ".*_knee_joint": 200.0,
            },
            damping={
                ".*_hip_yaw_joint": 5.0,
                ".*_hip_roll_joint": 5.0,
                ".*_hip_pitch_joint": 5.0,
                ".*_knee_joint": 5.0,
            },
        ),
        "feet": ImplicitActuatorCfg(
            joint_names_expr=[".*_ankle_pitch_joint", ".*_ankle_roll_joint"],
            effort_limit_sim=EFFORT_ANKLE,
            stiffness={".*_ankle_pitch_joint": 20.0, ".*_ankle_roll_joint": 20.0},
            damping={".*_ankle_pitch_joint": 4.0, ".*_ankle_roll_joint": 4.0},
        ),
        "waist": ImplicitActuatorCfg(
            joint_names_expr=["waist_roll_joint", "waist_yaw_joint"],
            effort_limit_sim=EFFORT_WAIST,
            stiffness={"waist_roll_joint": 20.0, "waist_yaw_joint": 20.0},
            damping={"waist_roll_joint": 4.0, "waist_yaw_joint": 4.0},
        ),
        "head": ImplicitActuatorCfg(
            joint_names_expr=["head_pitch_joint", "head_yaw_joint"],
            effort_limit_sim=EFFORT_HEAD,
            stiffness={"head_pitch_joint": 20.0, "head_yaw_joint": 20.0},
            damping={"head_pitch_joint": 4.0, "head_yaw_joint": 4.0},
        ),
        "arms": ImplicitActuatorCfg(
            joint_names_expr=[
                ".*_shoulder_pitch_joint",
                ".*_shoulder_roll_joint",
                ".*_shoulder_yaw_joint",
                ".*_elbow_joint",
                ".*_wrist_roll_joint",
            ],
            effort_limit_sim={
                ".*_shoulder_pitch_joint": EFFORT_SHOULDER,
                ".*_shoulder_roll_joint": EFFORT_SHOULDER,
                ".*_shoulder_yaw_joint": EFFORT_ARM_DISTAL,
                ".*_elbow_joint": EFFORT_ARM_DISTAL,
                ".*_wrist_roll_joint": EFFORT_ARM_DISTAL,
            },
            stiffness={
                ".*_shoulder_pitch_joint": 40.0,
                ".*_shoulder_roll_joint": 40.0,
                ".*_shoulder_yaw_joint": 40.0,
                ".*_elbow_joint": 40.0,
                ".*_wrist_roll_joint": 40.0,
            },
            damping={
                ".*_shoulder_pitch_joint": 10.0,
                ".*_shoulder_roll_joint": 10.0,
                ".*_shoulder_yaw_joint": 10.0,
                ".*_elbow_joint": 10.0,
                ".*_wrist_roll_joint": 10.0,
            },
        ),
    },
)
"""Configuration for the Unitree R1 humanoid (26 DOF, 27 bodies)."""

# =============================================================================
# Action scale
# =============================================================================
# Radians of joint-target travel per unit policy output.
#
# Deliberately NOT derived via g1.py's `0.25 * effort_limit_sim / stiffness`.
# That heuristic is calibrated to G1's armature-derived stiffnesses and does not
# transfer to R1's tested gains -- it yields 1.25-1.88 rad for the feet/waist/
# head/arms with the holosoma effort limits, or 0.075-0.10 rad for the legs with
# the real MJCF torque limits. G1's own per-joint scales span 0.35-0.55, so R1
# uses a flat value from the middle of that band.
#
# This is the first knob to touch if tracking is jittery (lower) or sluggish
# (raise); the gains above were tuned for locomotion, not whole-body tracking.
R1_DEFAULT_ACTION_SCALE = 0.4

R1_ACTION_SCALE = {
    joint_expr: R1_DEFAULT_ACTION_SCALE
    for actuator in R1_CFG.actuators.values()
    for joint_expr in actuator.joint_names_expr
}
